import { create } from 'zustand';

const useGameStore = create((set) => ({
  // 1. THE DATA SCHEMA
  player_progression: {
    current_epoch: 1, 
    world_corruption_discovered: 0.0, 
  },

  primitive_resources: {
    food: 50, // Starting higher so they don't starve instantly
    firewood: 10,
    flint: 0,
    culture: 0, // Generated by leisure
  },

  tribe_metrics: {
    population: 12,
    campfire_heat: 1.0, 
    fear_level: 0.10,   
    superstition_level: 1.0, 
    health_decay: 0.0, // Rises with agriculture
  },

  unlocked_knowledge: {
    agriculture_active: false,
    matrix_exposed: false,
  },

  // 2. LABOR ACTIONS (High Friction / High Yield)
  theGreatHunt: () => set((state) => {
    // Hunting takes a massive toll on fear and heat, but yields enough food for a week
    return {
      primitive_resources: {
        ...state.primitive_resources,
        food: state.primitive_resources.food + 40,
        flint: state.primitive_resources.flint + (Math.random() > 0.5 ? 1 : 0) // 50% chance for flint
      },
      tribe_metrics: {
        ...state.tribe_metrics,
        fear_level: Math.min(1.0, state.tribe_metrics.fear_level + 0.4),
        campfire_heat: Math.max(0, state.tribe_metrics.campfire_heat - 0.3)
      }
    };
  }),

  gatherWood: () => set((state) => ({
    primitive_resources: {
      ...state.primitive_resources,
      firewood: state.primitive_resources.firewood + 3
    }
  })),

  // 3. LEISURE ACTIONS (Psychological Maintenance)
  shareStories: () => set((state) => {
    if (state.tribe_metrics.campfire_heat > 0.5) {
      return {
        primitive_resources: {
          ...state.primitive_resources,
          culture: state.primitive_resources.culture + 1
        },
        tribe_metrics: {
          ...state.tribe_metrics,
          fear_level: Math.max(0, state.tribe_metrics.fear_level - 0.2),
          superstition_level: Math.min(1.0, state.tribe_metrics.superstition_level + 0.1)
        }
      };
    }
    return state; // Can't tell stories in the dark
  }),

  stokeFire: () => set((state) => {
    if (state.primitive_resources.firewood >= 1) {
      return {
        primitive_resources: { ...state.primitive_resources, firewood: state.primitive_resources.firewood - 1 },
        tribe_metrics: { ...state.tribe_metrics, campfire_heat: Math.min(1.0, state.tribe_metrics.campfire_heat + 0.5) }
      };
    }
    return state;
  }),

  // 4. THE TRAP (Unlocking Agriculture)
  discoverAgriculture: () => set((state) => {
    if (state.primitive_resources.culture >= 5 && state.primitive_resources.flint >= 2) {
      return {
        primitive_resources: {
          ...state.primitive_resources,
          culture: state.primitive_resources.culture - 5,
          flint: state.primitive_resources.flint - 2
        },
        unlocked_knowledge: {
          ...state.unlocked_knowledge,
          agriculture_active: true,
          matrix_exposed: true
        },
        player_progression: {
          ...state.player_progression,
          current_epoch: 2,
          world_corruption_discovered: 0.15
        }
      };
    }
    return state;
  }),

  // 5. THE ENGINE
  tick: () => set((state) => {
    let { campfire_heat, fear_level, population, health_decay } = state.tribe_metrics;
    let { food } = state.primitive_resources;
    let isAgri = state.unlocked_knowledge.agriculture_active;

    campfire_heat = Math.max(0, campfire_heat - 0.02);

    if (campfire_heat < 0.3) {
      fear_level = Math.min(1.0, fear_level + 0.05); 
    }

    // Food Consumption
    food = Math.max(0, food - (population * 0.2));

    // Agriculture Logic
    if (isAgri) {
      food += (population * 0.3); // Passive food generation
      health_decay = Math.min(1.0, health_decay + 0.01); // The biological toll of grains and labor
    }

    // Death Conditions
    if ((campfire_heat === 0 && fear_level >= 0.9) || food === 0 || health_decay >= 1.0) {
      if (Math.random() > 0.8 && population > 0) population -= 1;
    }

    return {
      primitive_resources: { ...state.primitive_resources, food: Number(food.toFixed(1)) },
      tribe_metrics: { ...state.tribe_metrics, campfire_heat: Number(campfire_heat.toFixed(2)), fear_level: Number(fear_level.toFixed(2)), health_decay: Number(health_decay.toFixed(2)), population }
    };
  })
}));

export default useGameStore;